version: 3
services:
  leave:
    image: leave-service
    ports:
      - 8075:8075

  mysql:
    image: mysql
    ports:
      - 3300:3300
    environment:
      -  MYSQL_ROOT_USER=root
      -  MYSQL_ROOT_PASSWORD=MainWill72
